# This is a basic workflow to help you get started with Actions

name: runner-linux
on:
  [workflow_dispatch, workflow_call]
jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - name: Run a one-line script
        timeout-minutes: 1
        run: echo Hello, world!
